library(ape) 
seq = read.dna(file='sequence-2.fasta', format = 'fasta') 
seq.str = as.vector(seq)
seq.str = gsub('48', 'g', seq.str)
seq.str = gsub('28', 'c', seq.str)
seq.str = gsub('18', 't', seq.str)
seq.str = gsub('88', 'a', seq.str)
seq.str = paste0(seq.str, collapse ='')
n = nchar(seq.str)
start_stop = n - 5
t = table(substring(seq.str, 1:start_stop, 6:n))
t_sort = sort(t, decreasing = TRUE)
names(head(t_sort, n = 2))
names(tail(t_sort, n = 2))
